import Image from "next/image";
import { Car, ChatCircleDots, CheckCircle, CurrencyCircleDollar, DeviceMobile, LockKey, MapPinLine, NavigationArrow, Package, ShieldCheck, UserFocus } from "@phosphor-icons/react/dist/ssr";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { SectionHeading } from "@/components/ui/section-heading";
import { HeroVisual } from "@/components/sections/hero-visual";
import { Faq } from "@/components/sections/faq";
import { RideModes } from "@/components/sections/ride-modes";
import { ActiveMap } from "@/components/sections/active-map";
import { DriverOpportunity } from "@/components/sections/driver-opportunity";
import { ViewportStage } from "@/components/ui/viewport-stage";
import { getAppAcquisitionHref, siteConfig } from "@/config/site";

const benefits = [
  [CurrencyCircleDollar, "Pricing choice", "Choose the ride and pricing experience that works for the moment."],
  [DeviceMobile, "Easy booking", "Set your pickup, choose your destination, and select how you want to ride."],
  [NavigationArrow, "Trip visibility", "Follow your active trip and keep the important details close."],
  [ChatCircleDots, "Stay connected", "Communicate with your matched driver during an active service."],
] as const;

export default function Home() {
  const structuredData = { "@context": "https://schema.org", "@type": "Organization", name: "Mova", url: siteConfig.url, description: siteConfig.description };
  return <main id="main-content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <section className="hero"><Container className="hero-grid"><div className="hero-copy"><p className="eyebrow">Mobility, made yours</p><h1>Move your <span>way.</span></h1><p className="hero-manifesto">Your ride. Your price. Your choice.</p><p className="hero-description">Request a ride, make an offer, choose a fixed-price trip, or go metered.</p><div className="hero-choices" aria-label="Mova ride pricing choices"><span>Make an offer</span><span>Fixed price</span><span>Metered</span></div><div className="button-row"><Button href={getAppAcquisitionHref()} arrow>Get Mova</Button><Button href="#ride-modes" variant="secondary">Explore ride modes</Button></div><div className="hero-proof"><span><MapPinLine size={20} weight="fill" />Launching in Nigeria</span><span><CheckCircle size={20} weight="fill" />Three ways to ride</span><span><ShieldCheck size={20} weight="fill" />Built around choice</span></div></div><HeroVisual /></Container></section>

    <RideModes />

    <section className="section section--muted"><Container><SectionHeading eyebrow="The Mova ecosystem" title="One Mova. More ways to move." align="center" />
      <div className="ecosystem-grid" role="region" aria-label="Mova services"><article className="ecosystem-card"><div className="ecosystem-photo"><Image src="/images/marketing/rider-placeholder.jpg" alt="A Mova rider travelling with a driver" fill sizes="(max-width: 767px) 87vw, (max-width: 1000px) 45vw, 33vw" /></div><div><p className="tag">For riders</p><h3>Ride</h3><p>Book a trip with the pricing approach that fits you.</p><Button href="/ride" variant="ghost" arrow>Explore rides</Button></div></article><article className="ecosystem-card"><div className="ecosystem-photo"><Image src="/images/marketing/driver-placeholder.jpg" alt="A driver at the wheel" fill sizes="(max-width: 767px) 87vw, (max-width: 1000px) 45vw, 33vw" /></div><div><p className="tag">For drivers</p><h3>Drive</h3><p>Find flexible opportunities and choose trips with clear information.</p><Button href="/drive" variant="ghost" arrow>Explore driving</Button></div></article><article className="ecosystem-card"><div className="ecosystem-photo"><Image src="/images/marketing/courier-placeholder.jpg" alt="A courier preparing a package" fill sizes="(max-width: 767px) 87vw, (max-width: 1000px) 45vw, 33vw" /></div><div><p className="tag">For deliveries</p><h3>Deliver</h3><p>Send packages or discover courier opportunities through Mova.</p><Button href="/deliver" variant="ghost" arrow>Explore delivery</Button></div></article></div><div className="mobile-carousel-dots" aria-hidden="true"><i className="is-current"/><i/><i/></div>
    </Container></section>

    <section className="section section--white"><Container className="rider-layout"><div className="rider-photo"><Image src="/images/marketing/rider-placeholder.jpg" alt="A rider enjoying a Mova journey" fill sizes="(max-width: 767px) 100vw, 48vw" /><div className="rider-status"><CheckCircle size={18} weight="fill"/><span><small>Active trip</small>Details close at hand</span></div></div><div><SectionHeading eyebrow="The rider experience" title="Wherever you’re headed, move on your terms." copy="From pickup to arrival, Mova keeps your options clear and your active trip information within reach." /><div className="benefit-list">{benefits.map(([Icon, title, copy]) => <div className="benefit" key={title}><span><Icon size={23} weight="duotone" /></span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></Container></section>

    <section className="section section--navy"><ViewportStage><Container className="driver-layout"><div><SectionHeading eyebrow="Drive with Mova" title="Your time. Your opportunities." copy="Find ride opportunities, see useful trip information, and choose what works for you—all on one Mova platform." inverse /><ul className="check-list"><li><CheckCircle />Flexible earning opportunities</li><li><CheckCircle />Choice over the trips you take</li><li><CheckCircle />Accept or counter where supported</li></ul><Button href="/drive" variant="inverse" arrow>Drive with Mova</Button></div><div className="driver-visual"><Image src="/images/marketing/driver-placeholder.jpg" alt="A Mova driver ready for a trip" fill sizes="(max-width: 767px) 100vw, 48vw" /><DriverOpportunity /></div></Container></ViewportStage></section>

    <section className="section courier-section"><Container className="courier-layout"><div className="courier-photo"><Image src="/images/marketing/courier-placeholder.jpg" alt="A courier preparing a package for delivery" fill sizes="(max-width: 767px) 100vw, 48vw" /><div className="parcel-status"><CheckCircle size={20} weight="fill" /><div><small>Delivery status</small><strong>Courier assigned</strong></div></div></div><div><SectionHeading eyebrow="Mova Courier" title="Fast, connected city parcel dispatch." copy="A clear delivery experience for people sending packages and couriers moving them through the city." /><div className="courier-audiences"><div><Package size={24}/><h3>For senders</h3><p>Arrange a package delivery and follow its active lifecycle.</p></div><div><UserFocus size={24}/><h3>For couriers</h3><p>Review delivery opportunities and useful assignment details.</p></div></div><Button href="/deliver" variant="secondary" arrow>Deliver with Mova</Button></div></Container></section>

    <section className="section section--white"><Container><div className="safety-panel"><div><SectionHeading eyebrow="Safety at every step" title="Move with greater confidence." copy="Mova is designed to keep relevant trip information visible and help riders and drivers stay connected during an active service." /><Button href="/safety" variant="secondary" arrow>Explore safety</Button></div><div className="safety-grid"><div><ShieldCheck /><h3>Trip visibility</h3><p>Follow key details through an active trip.</p></div><div><LockKey /><h3>Account security</h3><p>Protection designed into the Mova experience.</p></div><div><ChatCircleDots /><h3>Active communication</h3><p>Connect with your match when you need to.</p></div><div><UserFocus /><h3>Support access</h3><p>Find help and report an issue through Mova.</p></div></div></div></Container></section>

    <section className="section section--muted market-section"><ViewportStage><Container className="market-layout"><div className="market-copy"><div className="market-eyebrow"><MapPinLine size={14} weight="bold" aria-hidden="true" />SCALE &amp; FOOTPRINT</div><h2>Starting in Nigeria.<br />Built to go further.</h2><p className="market-description">Mova is launching first in Nigeria, with a platform designed to support more markets over time.</p><div className="market-status-list"><div><i/><span><strong>Nigeria</strong><small>First launch market</small></span><b>Launching first</b></div><div><i/><span><strong>Multi-market ready</strong><small>Country-aware services and pricing</small></span></div><div><i/><span><strong>Availability updates</strong><small>Confirmed cities will be published as rollout plans are finalised</small></span></div></div><Button href="/cities" variant="secondary" arrow>View market updates</Button></div><ActiveMap /></Container></ViewportStage></section>

    <section className="section app-section" id="get-mova"><ViewportStage><Container><SectionHeading eyebrow="The Mova app" title="Engineered for effortless control." copy="Illustrative product views show how rides, routes, and deliveries can come together in one focused experience." inverse align="center" /><div className="screen-showcase" role="region" aria-label="Mova app product screens"><div className="concept-screen"><small>Conceptual UI</small><h3>Select ride mode</h3><div className="screen-list"><span>Make an offer</span><span className="selected">Fixed price</span><span>Metered ride</span></div><button disabled>Request ride</button></div><div className="concept-screen concept-screen--center"><small>Conceptual UI</small><h3>Active journey</h3><div className="mini-map"><span/><Car size={22} weight="fill"/></div><p>Trip in progress</p></div><div className="concept-screen"><small>Conceptual UI</small><h3>Parcel progress</h3><div className="delivery-steps"><span className="done">Assigned</span><span className="done">Picked up</span><span>Delivered</span></div><button disabled>View delivery</button></div></div><div className="mobile-carousel-dots" aria-hidden="true"><i className="is-current"/><i/><i/></div><div className="store-row store-row--center"><button disabled><span>Coming soon on</span><strong>App Store</strong></button><button disabled><span>Coming soon on</span><strong>Google Play</strong></button></div></Container></ViewportStage></section>

    <section className="section section--white"><Container className="faq-layout"><SectionHeading eyebrow="Questions, answered" title="A few things to know about Mova." copy="Straightforward answers before your first trip." /><Faq /></Container></section>

    <section className="section section--white section--closing"><Container><div className="closing-cta"><p className="eyebrow">Move with Mova</p><h2>Ready to move your way?</h2><p>Your ride. Your price. Your choice.</p><div className="button-row"><Button href={getAppAcquisitionHref()} variant="inverse" arrow>Get Mova</Button><Button href="/drive" variant="ghost">Drive with Mova</Button></div></div></Container></section>
  </main>;
}
