export type LegalSection = { id: string; title: string; paragraphs: string[]; bullets?: string[] };

export type LegalDocument = {
  slug: "terms" | "ride" | "delivery" | "privacy";
  title: string;
  summary: string;
  sections: LegalSection[];
};

const draftNote = "Nigeria Launch Draft v1 — Pending Final Legal Review";

export const legalDocuments: LegalDocument[] = [
  {
    slug: "terms",
    title: "General Terms of Use",
    summary: "Platform-wide terms for using Mova technology and marketplace services in the Nigeria launch context.",
    sections: [
      { id: "agreement", title: "1. Agreement and scope", paragraphs: [`${draftNote}. These General Terms govern access to and use of the Mova website, mobile applications, platform services, and related technology features. Service-specific terms may supplement these Terms. Creating an account or using an applicable Mova service means you agree to the documents that apply to that use.`] },
      { id: "definitions", title: "2. Key definitions", paragraphs: ["Mova means the technology platform and marketplace operator. Platform means the software, websites, applications, tools, and related services made available by Mova. Rider means a user requesting transportation. Driver means an independent person who chooses to provide underlying transportation. Sender means a user requesting delivery. Recipient means the intended receiver of a delivery. Courier means an independent person who chooses to provide underlying delivery."] },
      { id: "mova-role", title: "3. Mova’s role as a technology marketplace", paragraphs: ["Mova operates a technology platform that connects people seeking mobility or delivery services with independent Drivers and Couriers who choose to provide those services. Mova operates the platform; the Driver or Courier performs the underlying transportation or delivery service.", "Mova may provide technology supporting matching, pricing mechanisms, offers and counteroffers, communications, payment facilitation, receipts, ratings, notifications, Safety features, tracking/status, and support. Providing these platform functions does not, by itself, mean that Mova physically drives a Rider, operates a Driver’s vehicle, carries a parcel, or delivers a parcel.", "Unless Mova expressly identifies a particular service as being provided directly by Mova, the underlying transportation or delivery arrangement is between the requesting user and the Driver or Courier, subject to applicable law and the service-specific terms." ] },
      { id: "independence", title: "4. Drivers and Couriers", paragraphs: ["Drivers and Couriers may choose whether and when to make themselves available and whether to accept individual opportunities, subject to applicable law, Mova platform rules, and service requirements. Nothing in these Terms overrides a classification, right, or protection that applicable law requires." ] },
      { id: "accounts", title: "5. Accounts and security", paragraphs: ["Users must provide information that is accurate enough for the relevant platform service, protect their credentials and verification codes, and promptly report suspected unauthorized access. Users should not impersonate another person or misuse another person’s account." ] },
      { id: "acceptable-use", title: "6. Acceptable use", paragraphs: ["Users must not use Mova for fraud, harassment, illegal activity, impersonation, unauthorized access, platform manipulation, security interference, or conduct that creates an unreasonable risk to another person or the platform." ] },
      { id: "platform-features", title: "7. Platform features and communications", paragraphs: ["Mova may provide in-app communications, push notifications, SMS, email, or other communications where supported. Features, availability, pricing mechanisms, and service options may vary by market, location, time, eligibility, and product configuration." ] },
      { id: "payments", title: "8. Payments and records", paragraphs: ["Mova may facilitate payment flows and provide electronic receipts or transaction records where applicable. Mova is not a bank. Payment processing may involve authorized third-party providers. Specific refund, cancellation, and dispute outcomes remain subject to the applicable service policy or disclosure." ] },
      { id: "safety-support", title: "9. Safety and support", paragraphs: ["Mova may provide Safety features, reporting paths, communications, and support tools. These features are intended to support users and do not guarantee that an incident cannot occur or replace reasonable care and compliance with law." ] },
      { id: "suspension", title: "10. Restrictions and termination", paragraphs: ["Mova may restrict or suspend platform access where reasonably necessary for fraud prevention, security, Safety, legal compliance, or serious platform-rule violations. Account closure does not remove obligations that should continue by their nature." ] },
      { id: "rights", title: "11. Intellectual property and user content", paragraphs: ["Mova retains rights in its name, logo, software, content, product interfaces, and technology. Where users submit ratings, support content, incident reports, profile material, or other content, they grant only the permissions reasonably needed to host, process, display, moderate, and operate the platform." ] },
      { id: "consumer-rights", title: "12. Disclaimers, liability, and consumer rights", paragraphs: ["Platform availability, route information, estimates, and third-party infrastructure may be affected by real-world or technical conditions. Nothing in these Terms excludes or limits rights, remedies, or liability that cannot lawfully be excluded or limited under applicable law. Any final liability, indemnity, dispute, and governing-law provisions require counsel confirmation." ] },
      { id: "changes", title: "13. Changes and unresolved legal details", paragraphs: ["Mova may update these Terms with appropriate notice where required. The following remain to be confirmed: [MOVA LEGAL ENTITY], [MOVA REGISTERED ADDRESS], [MOVA COMPANY NUMBER], [MOVA LEGAL EMAIL], [MINIMUM USER AGE], and [GOVERNING LAW / JURISDICTION — COUNSEL TO CONFIRM]."] },
    ],
  },
  {
    slug: "ride",
    title: "Ride Terms",
    summary: "Service-specific draft terms supplementing the General Terms for Mova Ride.",
    sections: [
      { id: "ride-platform", title: "1. Mova Ride platform", paragraphs: ["Mova provides technology through which Riders create ride requests and eligible Drivers choose whether to respond to or accept opportunities. The Driver performs the underlying physical transportation service; Mova operates the platform." ] },
      { id: "make-an-offer", title: "2. Make an Offer", paragraphs: ["A Rider may propose a fare within supported Mova marketplace rules, including any applicable floors, ranges, or limits. An eligible Driver may accept or counter where supported. Mova provides the technology and rules for this exchange but does not compel either party to agree. Final contract-formation wording requires counsel review." ] },
      { id: "fixed-price", title: "3. Fixed Price", paragraphs: ["Mova may calculate and display an upfront fare using route information, pricing parameters, marketplace conditions, and other applicable factors. The Rider chooses whether to request at that price and an eligible Driver chooses whether to accept the opportunity. Mova presenting or calculating a fare does not mean Mova physically performs transportation." ] },
      { id: "metered-ride", title: "4. Metered Ride", paragraphs: ["Mova may show an estimate before a Metered Ride. The final fare is determined through the platform using validated journey information and applicable metered pricing rules, which may reflect distance, duration, and disclosed components. Route, distance, duration, and ETA estimates may differ from actual conditions." ] },
      { id: "rider-driver", title: "5. Rider and Driver responsibilities", paragraphs: ["Riders should provide accurate pickup and destination information, act lawfully and respectfully, use reasonable care in a Driver’s vehicle, and meet payment obligations. Drivers are responsible, subject to applicable law and platform requirements, for lawful driving, licensing, vehicle operation, vehicle condition, traffic-law compliance, and professional conduct." ] },
      { id: "cancellation", title: "6. Cancellations and completion", paragraphs: ["Mova may provide cancellation, waiting, stop, receipt, rating, and support functionality. Any applicable cancellation or waiting charge will be disclosed through the platform or applicable policy; no amount is specified in this draft. Mova does not guarantee Driver availability or acceptance." ] },
    ],
  },
  {
    slug: "delivery",
    title: "Delivery & Courier Terms",
    summary: "Service-specific draft terms for Senders, Recipients, and Couriers using Mova Delivery.",
    sections: [
      { id: "delivery-platform", title: "1. Delivery platform role", paragraphs: ["Mova provides technology through which Senders create delivery requests and independent Couriers choose whether to accept and perform them. Unless Mova expressly identifies a service as direct, Mova does not itself collect, carry, transport, or deliver the parcel. The Courier performs the underlying physical delivery service." ] },
      { id: "sender", title: "2. Sender responsibilities", paragraphs: ["Senders are responsible for accurate pickup and recipient information, lawful parcel contents, appropriate packaging, accurate descriptions where requested, reasonable access for collection, and payment obligations. Senders should not provide unnecessary personal information about a Recipient." ] },
      { id: "recipient", title: "3. Recipient participation", paragraphs: ["Where a Recipient’s phone number corresponds to an existing Mova account, Mova may associate that user with the active delivery for supported participation, such as in-app notifications, delivery visibility, Courier information, progress, and completion information. These capabilities depend on the product and applicable rules." ] },
      { id: "external-recipient", title: "4. External Recipients", paragraphs: ["A Recipient without a Mova account does not automatically become a registered Mova user merely because a Sender provides contact information. Mova may process that information only as permitted for arranging delivery, collection or handoff, communications, Safety, support, legal, and security purposes. An external Recipient is not casually treated as having accepted the full Mova Terms." ] },
      { id: "courier", title: "5. Courier responsibilities", paragraphs: ["Couriers are responsible, subject to applicable law and platform requirements, for lawful operation, appropriate equipment or vehicle, reasonable parcel care, pickup verification where supported, delivery to the intended Recipient or location, professional conduct, Safety, and accurate completion information. Courier independence does not remove Mova’s responsibilities for the platform it operates." ] },
      { id: "parcels", title: "6. Parcel rules", paragraphs: ["Senders must not request delivery of illegal goods, stolen property, prohibited weapons or explosives, controlled or illegal drugs, dangerous or hazardous substances, human remains, living persons, or other items prohibited by law or Mova policy. Regulated goods may require permits or special handling. [HIGH-VALUE / EXCLUDED ITEMS POLICY — TO BE CONFIRMED]." ] },
      { id: "tracking", title: "7. Pricing, tracking, and completion", paragraphs: ["Mova may facilitate pricing, communications, delivery status, tracking, notifications, and completion records. Pricing and delivery estimates are displayed through the platform where appropriate and are not guaranteed. Tracking may be unavailable or inaccurate in some circumstances." ] },
      { id: "loss-damage", title: "8. Delivery issues", paragraphs: ["Users should report non-delivery, wrong-recipient, damage, or other disputes through available Mova support. Final rules for returns, redelivery, refunds, insurance, declared value, and loss or damage liability remain unresolved: [RETURN / REDELIVERY POLICY — TO BE CONFIRMED], [MAXIMUM PARCEL VALUE / LIABILITY POLICY — TO BE CONFIRMED], [DELIVERY LOSS / DAMAGE LIABILITY TERMS — COUNSEL AND BUSINESS TO CONFIRM], and [INSURANCE POSITION — BUSINESS/COUNSEL TO CONFIRM]." ] },
    ],
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    summary: "Draft explanation of how Mova may handle personal information across its platform ecosystem.",
    sections: [
      { id: "scope", title: "1. Scope and controller", paragraphs: ["This Nigeria Launch Draft describes information handling for the public website, Mova applications, platform services, support, Safety functionality, and related ecosystem features. The controller/operator is [MOVA LEGAL ENTITY], [MOVA REGISTERED ADDRESS]. Privacy contact: [MOVA PRIVACY EMAIL]. This document requires review against the Nigeria Data Protection Act and applicable requirements." ] },
      { id: "data-categories", title: "2. Information Mova may process", paragraphs: ["Depending on the service, Mova may process account and identity information, contact and profile information, Rider, Driver, and Courier information, location and trip information, delivery and Recipient information, payment or transaction records, communications, ratings and feedback, Safety and incident information, support information, device and technical information, and fraud or security information. Mova should not collect more information than the relevant purpose requires." ] },
      { id: "location", title: "3. Location information", paragraphs: ["Mova’s mobile applications may process precise location when needed for supported pickup, matching, trip or delivery execution, route/status information, Safety, fraud/security, or support functions, subject to device permissions, app role, product state, and applicable law. The public marketing website does not require precise browser geolocation. [BACKGROUND LOCATION RULES — CONFIRM AGAINST FINAL MOBILE IMPLEMENTATION]." ] },
      { id: "trip-delivery", title: "4. Trip, delivery, and Recipient information", paragraphs: ["Trip information may include pickup, destination, route, timestamps, ride mode, fare, status, cancellation, and completion. Delivery information may include Sender, pickup, Recipient details, destination, Courier, status, timestamps, route, and completion. A Sender may provide a Recipient’s name, phone number, destination, or other information needed to arrange delivery. Existing Mova Recipients may receive supported delivery participation; external Recipients do not automatically receive an account." ] },
      { id: "uses", title: "5. How Mova may use information", paragraphs: ["Mova may use information to provide platform services, manage accounts, match users, support rides and deliveries, calculate or display pricing, facilitate payments, send communications, provide Safety and support, prevent fraud and security incidents, comply with law, improve reliability where lawful, and exercise or defend legal rights. Final legal bases require counsel review and may include contract, legal obligations, legitimate interests, consent where required, and protection of vital interests where applicable." ] },
      { id: "sharing", title: "6. Sharing information", paragraphs: ["Information may be shared as needed among matched Riders, Drivers, Senders, Couriers, and Recipients; with communications, payment, cloud, security, support, and infrastructure providers; with professional advisers; with authorities where legally required; and with business-transfer counterparties where applicable. Mova should not expose more personal information than the relevant platform purpose requires. Provider categories may change by country." ] },
      { id: "communications", title: "7. Communications and security", paragraphs: ["Mova may send account, OTP/security, trip, delivery, support, Safety, and transactional communications through push notifications, SMS, email, or in-app channels where supported. Mova uses technical and organizational safeguards designed to protect information, but no system can promise absolute security. Mova may process information to protect accounts, detect fraud, prevent abuse, and investigate suspicious activity." ] },
      { id: "retention", title: "8. Retention and deletion", paragraphs: ["Mova retains information for as long as reasonably needed for service, account, legal, fraud/security, financial recordkeeping, dispute, Safety, and limitation-period purposes. [DATA RETENTION SCHEDULE — TO BE CONFIRMED]. Users may request account deletion, subject to lawful retention and other applicable obligations. Final account-deletion behavior must be compared with the mobile applications." ] },
      { id: "rights", title: "9. Privacy rights", paragraphs: ["Subject to applicable law, users may have rights to access, correct, delete, restrict, object to processing, withdraw consent where processing relies on consent, complain, and exercise other statutory rights. Mova may verify identity before acting. Requests should be directed to [MOVA PRIVACY EMAIL]. Users may also have the right to complain to the applicable Nigerian data-protection authority." ] },
      { id: "children", title: "10. Children and changes", paragraphs: ["The platform is not intended for people below [MINIMUM USER AGE], except where a specific approved product flow provides otherwise and applicable law permits it. Mova may update this Policy with appropriate notice. Final review must cover permissions, background location, push tokens, device identifiers, analytics or crash tools, payments, account deletion, international transfers, retention, and Recipient behavior in the completed mobile applications." ] },
    ],
  },
];

export const legalDraftLabel = draftNote;
export const legalDraftDate = "Draft generated 15 September 2026";
export const legalDocumentsBySlug = Object.fromEntries(legalDocuments.map((document) => [document.slug, document])) as Record<LegalDocument["slug"], LegalDocument>;
